import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nonito = Nunito({
  variable: "--font-nonito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nonito.className}>{children}</body>
    </html>
  );
}
